### ISSUE TITLE
下载非中英文歌曲名的歌词时会出错

### ISSUE THREAD

**Issue by kimycai** [GameBelial/ZonyLrcToolsX#112]
比如歌曲名为纯韩文的歌词时，就下载不了歌词
https://y.qq.com/n/ryqq/songDetail/001PjDvf0INONp
比如这首就不行
也许纯日文的也下载不了
不知道能不能解决？
以下是下载报告，共六首歌，两首是纯韩文的下载失败
--------------------------------------报告--------------------------------------------
[14:02:00 INF] 已经扫描到了 6 个音乐文件。
[14:02:00 INF] 开始加载音乐文件的标签信息...
[14:02:00 INF] 已成功加载 6 个音乐文件的标签信息。
[14:02:00 INF] 开始下载歌词文件数据...
[14:02:01 INF] 歌曲名: Like a Fool, 艺术家: TWICE, 下载成功.
[14:02:01 INF] 歌曲名: Candy Boy, 艺术家: TWICE, 下载成功.
[14:02:01 WRN] 错误代码: 50004，信息: 下载器没有搜索到对应的歌曲信息。
附加信息:
 {"SongName":"????","Artist":"TWICE"}
[14:02:01 INF] 歌曲名: ????, 艺术家: TWICE, 下载成功.
[14:02:01 INF] 歌曲名: Truth, 艺术家: TWICE, 下载成功.
[14:02:01 WRN] 错误代码: 50004，信息: 下载器没有搜索到对应的歌曲信息。
附加信息:
 {"SongName":"?? ??","Artist":"TWICE"}
[14:02:01 INF] 歌曲名: ?? ??, 艺术家: TWICE, 下载成功.
[14:02:02 INF] 歌曲名: Like OOH-AHH, 艺术家: TWICE, 下载成功.
[14:02:02 INF] 歌词数据下载完成，成功: 6 失败0。

**Comment by kimycai** [comment]
我的歌词下载优先级是QQ为1，网易为2

**Comment by real-zony** [comment]
@kimycai  可能是标签解析器出现的问题，出现这种情况的时候，建议禁用掉 taglib 加载器，并使用文件名作为 tag 来源，配置参考。
```YAML
  # 下载器的相关参数配置。
  provider:
    # 标签扫描器的相关参数配置。
    tag:
      # 支持的标签扫描器。
      plugin:
        - name: Taglib    # 基于 Taglib 库的标签扫描器。
          priority: -1     # 优先级，升序排列。
        - name: FileName  # 基于文件名的标签扫描器。
          priority: 2
          # 基于文件名扫描器的扩展参数。
          extensions:
            # 正则表达式，用于匹配文件名中的作者信息和歌曲信息，可根据
            # 自己的需求进行调整。
            regularExpressions: "(?'artist'.+)\\s-\\s(?'name'.+)"
```
