### ISSUE TITLE
下载英文歌歌词时能否选择不下载翻译

### ISSUE THREAD

**Issue by Jackietiger0320** [GameBelial/ZonyLrcToolsX#114]
zony大佬你好，你的这个项目真的很棒，我已捐赠10元以表谢意
我想问下下载英文歌歌词时能否只下载英文，因为部分翻译是乱码，而且MP3屏幕较小，没有翻译的话观感更好
我也试了下手动删英文但效率太低
网上有一些删除txt中的汉字的代码行但我还是高中生不太会用
如果你有空闲，可否在QQ上向你求助呢

**Comment by real-zony** [comment]
@Jackietiger0320  只需要更改 config.yaml 里面的配置，设置不执行翻译操作即可。
```YAML
globalOption:
    provider:
      config:
        isEnableTranslation: false # 是否启用翻译歌词。
```
